name: songtube
description: A new Flutter project.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 6.5.0+1400

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    # Error reporting
    # sentry_flutter: ^4.0.6

    # Media Playback Packages
    flutter_audio_query: 
        git: 
            url: https://github.com/Mayb3Nots/flutter_audio_query
            ref: master
    video_player:
        git:
            url: https://github.com/SongTube/video_player
            ref: master

    just_audio: ^0.9.30
    audio_service:
        git:
            url: https://github.com/SongTube/audio_service-1
            ref: master


    # NewPipe Extractor
    newpipeextractor_dart:
        path: ../NewPipeExtractor_Dart

    # Device Providers
    shared_preferences: ^2.0.15 
    provider: ^6.0.5
    device_info: ^2.0.3
    path_provider: ^2.0.11
    package_info: ^2.0.2
    external_path: ^1.0.3
    permission_handler: ^10.2.0 
    file_picker: ^5.2.4
    path: ^1.8.2

    # Text
    intl: ^0.17.0
    string_validator: ^0.3.0
    google_fonts: ^3.0.1

    # HTTP
    dio: ^4.0.6
    http: ^0.13.5
    flutter_inappwebview: ^5.7.2+3
    flutter_html:
        git:
            url: https://github.com/SongTube/flutter_html

    # Icons
    material_design_icons_flutter: ^6.0.7096
    eva_icons_flutter: ^3.1.0

    # Animations
    shimmer: ^2.0.0
    avatar_glow: ^2.0.2
    flutter_glow: ^0.2.0
    autolist:
        git:
            url: https://github.com/SongTube/autolist
            ref: master
    image_fade: ^0.6.2
    animations: ^2.0.7
    loading_indicator: ^3.1.0

    # Tools
    flutter_share: ^2.0.0
    audio_tagger: ^2.2.1

    share: ^2.0.4
    flutter_ffmpeg: ^0.4.2
    url_launcher: ^6.1.7
    transparent_image: ^2.0.0
    grouped_list: ^5.1.2
    volume:
        git:
            url: https://github.com/mackhan007/Volume_Flutter
            ref: macky
    flutter_screen:
        git:
            url: https://github.com/SongTube/flutter_screen
            ref: master
    flutter_pip:
        git:
            url: https://github.com/Artx-II/flutter_pip
            ref: main
    file_operations:
        git:
            url: https://github.com/SongTube/file_operations
            ref: main
    apk_installer:
        git:
            url: https://github.com/SongTube/apk_installer
            ref: main

    # Database
    sqflite: ^2.2.2

    # Misc
    flutter_xlider:
        git:
            url: https://github.com/swaroopsuthar/flutter_xlider.git
            ref: master
    flutter_material_color_picker: ^1.1.0+2
    flutter_keyboard_visibility: ^5.4.0
    flutter_staggered_grid_view: ^0.6.2
    palette_generator: ^0.3.3+2
    flutter_markdown: ^0.6.13
    md2_tab_indicator:
        git:
            url: https://github.com/abdelrahmanelmarakby/md2_tab_indicator
            ref: patch-1
    collection: ^1.15.0-nullsafety.4

dependency_overrides:
  platform: ^3.1.0
  flutter_math_fork: ^0.5.0
  html: ^0.15.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/
        - assets/LICENSE
    #  - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    fonts:
        - family: YTSans
          fonts:
              - asset: assets/fonts/youtube-sans-medium.ttf
                weight: 500
              - asset: assets/fonts/youtube-sans-light.ttf
                weight: 300
              - asset: assets/fonts/youtube-sans-bold.ttf
                weight: 700
        - family: Product Sans
          fonts:
              - asset: assets/fonts/productSans/bold.ttf
                weight: 700
              - asset: assets/fonts/productSans/regular.ttf
                weight: 400
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
